### ISSUE TITLE
Hello, i can help

### ISSUE THREAD

**Issue by ghost** [GregLando113/kenshi-reclaimer#1]
Hello, I would like to contact the developers regarding this repository. I would like to help advance the reverse engineering of kenshi.

Sorry for offtop.
My contact:
Discord: DocNight#8500

**Comment by BFrizzleFoShizzle** [comment]
Hi, sorry for the late reply, 
If neither Greg/Kaos or I have replied to you yet, I just sent you a friend request on discord. Most of the team's discussion has been happening on the Project Genesis discord server at https://discord.com/invite/g7F6aHw
Let me know if you have any issues getting in touch with us, we're always keen to pick up more contributors!
